# Python Data Structures tutorial

1. [Introduction to lists](#1)
2. [Modify lists](#2)
3. [Introduction to NumPy](#3)
4. [Basic array operations](#4)
5. [Introduction to pandas](#5)
6. [Pandas basics](#6)

<a id = '1'> </a> </br>*
## 1-Introduction to lists

In [1]:
# assign a list
myList = ['A','B','C','D']
#look list
myList
#print index 2
print(myList[2])

C


In [2]:
# try to access index not in list - you get index error
print(myList[10])

IndexError: list index out of range

In [3]:
# slicing
myList[0:2]

['A', 'B']

In [4]:
# getting datas from 0- 0:A , 1:B
myList[:2]

['A', 'B']

In [5]:
# getting datas from after 2 index to end of list
myList[2:]

['C', 'D']

In [6]:
# check data type
type(myList)

list

In [7]:
myList

['A', 'B', 'C', 'D']

In [8]:
# check with 'in' if a value in list
'W' in myList

False

<a id = '2'> </a> </br>
## 2- Modify list

In [9]:
fruits = ['Apple', 'Banana']
fruits

['Apple', 'Banana']

In [10]:
# append() - adds elemnt end of list
fruits.append('Kiwi')
print(fruits)

['Apple', 'Banana', 'Kiwi']


In [11]:
# insert() adds element to list at spacified index
fruits.insert(1, 'Orange')
print(fruits)

['Apple', 'Orange', 'Banana', 'Kiwi']


In [12]:
# remove() method deletes an element list
fruits.remove('Banana')
print(fruits)

['Apple', 'Orange', 'Kiwi']


In [13]:
# trying to remove an element that doesn't exist return error
fruits.remove('Banana')
print(fruits)

ValueError: list.remove(x): x not in list

In [14]:
fruits

['Apple', 'Orange', 'Kiwi']

In [15]:
# pop() method removes elemnt given index and return it
# if no index given it removes last element
fruits.pop(2)
print(fruits)

['Apple', 'Orange']


In [16]:
# reassign element to given index
fruits[1]='Kiwi'
print(fruits)

['Apple', 'Kiwi']


In [17]:
# strings modify
power = '1.21'
power = power+' gigawatts'
print(power)

1.21 gigawatts


In [18]:
# you cant reassign spacific character with a string
power[0]='2'

TypeError: 'str' object does not support item assignment

In [19]:
# list are mutable because you can overwrite elements
power = [1.21, 'gigawatts']
power

[1.21, 'gigawatts']

In [20]:
power[0]=2.21
print(power)

[2.21, 'gigawatts']


<a id = '3'> </a> </br>
## 3- Introduction to NumPy

In [21]:
# list cant multiplied together
list_a = [1,2,3]
list_b = [2,4,6]

list_a*list_b

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
# for multipication with two list we can use 'for loop'
list_c = []
for i in range(len(list_a)):
    list_c.append(list_a[i] * list_b[i])

list_c

[2, 8, 18]

In [23]:
# we can arrays operations with NumPy

#import numpy
import numpy as np

#convert lists to arrays
array_a = np.array(list_a)
array_b = np.array(list_b)

array_a* array_b

array([ 2,  8, 18])

<a id = '4'> </a> </br>
## 4- Basic array operations

In [24]:
# np.array() 
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [25]:
# array change with index
# we change last element - 4 change to 5
x[-1] = 5
x

array([1, 2, 3, 5])

In [26]:
# try to acces index that doesn't exist gives error
x[10] = 25

IndexError: index 10 is out of bounds for axis 0 with size 4

In [27]:
array1 = np.array([1,2,'Banana'])
array1

array(['1', '2', 'Banana'], dtype='<U11')

In [28]:
# numpy arrays are class of numpy'numpy.ndarray'
print(type(array1))

<class 'numpy.ndarray'>


In [29]:
array1 = np.array([1,2,3])
array1.dtype

dtype('int32')

In [30]:
# shape() returns elements each dimension
array1.shape

(3,)

In [31]:
# ndim() returns number of dimensions in array
array1.ndim

1

In [32]:
# create 2d array 
array_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(array_2d.shape)
print(array_2d.ndim)
array_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
# create 3d array
array_3d = np.array([[[1,2,3],
                     [3,4,5]],
                     
                    [[5,6,7],
                     [7,8,9]]]
                   )

print(array_3d.shape)
print(array_3d.ndim)
array_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [34]:
# reshape() changes shape of array
array_2d = array_2d.reshape(2,4)
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# create new array
array_new = np.array([1,2,3,4,5])

# mean() return mean of array
np.mean(array_new)

3.0

In [36]:
# log() return logartihm of elements in array
np.log(array_new)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [37]:
# floor() retrun value of number rounded down to nearest integer
print(np.floor(1.3))

print(np.floor(2.7))

1.0
2.0


In [38]:
# ceil() retrun value of number rounded up to nearest integer
np.ceil(4.3)

5.0

<a id = '5'> </a> </br>
## 5- Introduction to pandas

In [39]:
# import libraries
import pandas as pd
import numpy as np

C:\Users\suubc\AppData\Local\Temp\ipykernel_7176\866360625.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [40]:
# read data
dataframe = pd.read_csv('titanicv2/train.csv')

# print first 10 rows
dataframe.head(10) 

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [41]:
# calculate age mean
dataframe['Age'].mean()

29.69911764705882

In [42]:
# calculate max age
dataframe['Age'].max()

80.0

In [43]:
# calculate min age
dataframe['Age'].min()

0.42

In [44]:
# calculate standard deviation of age
dataframe['Age'].std()

14.526497332334042

In [45]:
# return number of rows share same value in Pclass
dataframe['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [46]:
# describe() return summary statistics of df
dataframe.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [47]:
# filter data age greater than 70
dataframe[(dataframe['Age'] >70 )]

PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S

In [48]:
# filter age and plass
dataframe[(dataframe['Age'] < 25) & (dataframe['Pclass'] == 1)]

PassengerId  Survived  Pclass  \
27            28         0       1   
88            89         1       1   
97            98         1       1   
102          103         0       1   
118          119         0       1   
136          137         1       1   
139          140         0       1   
151          152         1       1   
291          292         1       1   
297          298         0       1   
305          306         1       1   
307          308         1       1   
310          311         1       1   
311          312         1       1   
329          330         1       1   
341          342         1       1   
356          357         1       1   
369          370         1       1   
373          374         0       1   
393          394         1       1   
435          436         1       1   
445          446         1       1   
504          505         1       1   
505          506         0       1   
539          540         1       1   
550          551         1       1   
585          586         1       1   
627          628         1       1   
641          642         1       1   
689          690         1       1   
700          701         1       1   
708          709         1       1   
710          711         1       1   
742          743         1       1   
748          749         0       1   
781          782         1       1   
802          803         1       1   
853          854         1       1   
887          888         1       1   

                                                  Name     Sex    Age  SibSp  \
27                      Fortune, Mr. Charles Alexander    male  19.00      3   
88                          Fortune, Miss. Mabel Helen  female  23.00      3   
97                     Greenfield, Mr. William Bertram    male  23.00      0   
102                          White, Mr. Richard Frasar    male  21.00      0   
118                           Baxter, Mr. Quigg Edmond    male  24.00      0   
136                       Newsom, Miss. Helen Monypeny  female  19.00      0   
139                                 Giglio, Mr. Victor    male  24.00      0   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.00      1   
291            Bishop, Mrs. Dickinson H (Helen Walton)  female  19.00      1   
297                       Allison, Miss. Helen Loraine  female   2.00      1   
305                     Allison, Master. Hudson Trevor    male   0.92      1   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.00      1   
310                     Hays, Miss. Margaret Bechstein  female  24.00      0   
311                         Ryerson, Miss. Emily Borie  female  18.00      2   
329                       Hippach, Miss. Jean Gertrude  female  16.00      0   
341                     Fortune, Miss. Alice Elizabeth  female  24.00      3   
356                        Bowerman, Miss. Elsie Edith  female  22.00      0   
369                      Aubart, Mme. Leontine Pauline  female  24.00      0   
373                                Ringhini, Mr. Sante    male  22.00      0   
393                             Newell, Miss. Marjorie  female  23.00      1   
435                          Carter, Miss. Lucile Polk  female  14.00      1   
445                          Dodge, Master. Washington    male   4.00      0   
504                              Maioni, Miss. Roberta  female  16.00      0   
505         Penasco y Castellana, Mr. Victor de Satode    male  18.00      1   
539                 Frolicher, Miss. Hedwig Margaritha  female  22.00      0   
550                        Thayer, Mr. John Borland Jr    male  17.00      0   
585                                Taussig, Miss. Ruth  female  18.00      0   
627                      Longley, Miss. Gretchen Fiske  female  21.00      0   
641                               Sagesser, Mlle. Emma  female  24.00      0   
689                  Madill, Miss. Georgette Alexandra  female  15.00      0   
700 

In [49]:
# iloc to access data index number
# select row 2, column 4 
dataframe.iloc[5][3]

C:\Users\suubc\AppData\Local\Temp\ipykernel_7176\673463225.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dataframe.iloc[5][3]


'Moran, Mr. James'

In [50]:
# group customers by Sex and Pclass - calculate total paid for each group
# and mean price for each group
fare = dataframe.groupby(['Sex', 'Pclass']).agg({'Fare': ['count', 'sum']})
fare['fare_avg'] = fare['Fare']['sum'] / fare['Fare']['count']
fare

Fare               fare_avg
              count        sum            
Sex    Pclass                             
female 1         94  9975.8250  106.125798
       2         76  1669.7292   21.970121
       3        144  2321.1086   16.118810
male   1        122  8201.5875   67.226127
       2        108  2132.1125   19.741782
       3        347  4393.5865   12.661633

<a id = '6'> </a> </br>
## 6- Pandas basics

In [51]:
import pandas as pd
# pd.Dataframe() create  df from dict
data = {'col1': [1,2], 'col2':[3,4]}
df = pd.DataFrame(data=data)
df

col1  col2
0     1     3
1     2     4

In [52]:
# pd.Dataframe() create from numpy array
df2 = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns=['a','b','c'], index=['x','y','z'])
df2

a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [53]:
df3 = pd.read_csv('titanicv2/train.csv')
df3.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [54]:
# print class first row
print(type(df3.iloc[0]))

print(type(df3['Name']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [55]:
# create copy of df3
titanic = df3
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [56]:
# df columns
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [57]:
# shape of df
titanic.shape

(891, 12)

In [58]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [59]:
# you can check by name
titanic['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [60]:
titanic.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [61]:
# create dataframe spacific columns
titanic[['Name','Age']]

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [62]:
# iloc to data in row 6
titanic.iloc[6]

PassengerId                          7
Survived                             0
Pclass                               1
Name           McCarthy, Mr. Timothy J
Sex                               male
Age                               54.0
SibSp                                0
Parch                                0
Ticket                           17463
Fare                           51.8625
Cabin                              E46
Embarked                             S
Name: 6, dtype: object

In [63]:
# just for row 6
titanic.iloc[[6]]

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
6            7         0       1  McCarthy, Mr. Timothy J  male  54.0      0   

   Parch Ticket     Fare Cabin Embarked  
6      0  17463  51.8625   E46        S

In [64]:
# use for viewm row 2,3,4
titanic.iloc[2:5]

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
2                        Heikkinen, Miss. Laina  female  26.0      0      0   
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   

             Ticket    Fare Cabin Embarked  
2  STON/O2. 3101282   7.925   NaN        S  
3            113803  53.100  C123        S  
4            373450   8.050   NaN        S

In [65]:
# view row 2-4 and columns 4-5
titanic.iloc[2:5, [4,5]]

Sex   Age
2  female  26.0
3  female  35.0
4    male  35.0

In [66]:
# iloc view all data rows at spacific columns
titanic.iloc[:,[5]]

Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

In [67]:
# access row x columns x
titanic.iloc[2,3]

'Heikkinen, Miss. Laina'

In [68]:
# loc to access rows x-x at x columns 
titanic.loc[0:3, ['Age']]

Age
0  22.0
1  38.0
2  26.0
3  35.0

In [69]:
# create column value of age +100
titanic['Age_plus_100'] = titanic['Age'] + 100
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_plus_100  
0      0         A/5 21171   7.2500   NaN        S         122.0  
1      0          PC 17599  71.2833   C85        C         138.0  
2      0  STON/O2. 3101282   7.9250   NaN        S         126.0  
3      0            113803  53.1000  C123        S         135.0  
4      0            373450   8.0500   NaN        S         135.0